const modules = [
  {
    id: 1,
    category: "Fundamental Rights",
    icon: "⚖️",
    article: "14",
    title: "Right to Equality",
    description: "No citizen can be discriminated against on religion, caste, gender or birthplace.",
    progress: 100,
    duration: "15 min",
    lessons: 5,
    users: 4821,
    rating: 4.9,
    level: "Beginner",
  },

  {
    id: 2,
    category: "Fundamental Rights",
    icon: "🗣️",
    article: "19",
    title: "Freedom of Speech & Expression",
    description: "You can speak, write and express opinions freely within reasonable restrictions.",
    progress: 70,
    duration: "18 min",
    lessons: 6,
    users: 3950,
    rating: 4.8,
    level: "Beginner",
  },

  {
    id: 3,
    category: "Police & Arrest Rights",
    icon: "👮",
    article: "22",
    title: "Rights During Arrest",
    description: "Police must inform grounds of arrest and allow access to a lawyer within 24 hours.",
    progress: 0,
    duration: "20 min",
    lessons: 7,
    users: 6120,
    rating: 4.9,
    level: "Important",
  },

  {
    id: 4,
    category: "FIR & Complaints",
    icon: "📄",
    article: "",
    title: "How to File an FIR",
    description: "Steps to file FIR at police station or online. Police cannot refuse cognizable complaints.",
    progress: 0,
    duration: "22 min",
    lessons: 8,
    users: 7100,
    rating: 4.7,
    level: "Important",
  },

  {
    id: 5,
    category: "Women Rights",
    icon: "👩",
    article: "",
    title: "Women Safety Laws",
    description: "Protection against harassment, domestic violence and workplace misconduct.",
    progress: 0,
    duration: "25 min",
    lessons: 9,
    users: 8421,
    rating: 4.9,
    level: "Intermediate",
  },

  {
    id: 6,
    category: "Consumer Rights",
    icon: "🛒",
    article: "",
    title: "Consumer Protection Act",
    description: "Return defective products, claim refund, and file complaint in consumer court.",
    progress: 0,
    duration: "16 min",
    lessons: 5,
    users: 5300,
    rating: 4.8,
    level: "Intermediate",
  },

  {
    id: 7,
    category: "Cyber Crime",
    icon: "💻",
    article: "",
    title: "Online Fraud & Cyber Complaints",
    description: "Report cyber scams, OTP fraud and social media harassment legally.",
    progress: 0,
    duration: "17 min",
    lessons: 6,
    users: 9230,
    rating: 4.9,
    level: "Important",
  },

  {
    id: 8,
    category: "Court Procedures",
    icon: "🏛️",
    article: "",
    title: "What Happens After Filing a Case",
    description: "Understand hearings, evidence, arguments, judgement and appeal process.",
    progress: 0,
    duration: "24 min",
    lessons: 8,
    users: 4100,
    rating: 4.7,
    level: "Intermediate",
  },

  {
    id: 9,
    category: "Public Interest Litigation",
    icon: "📜",
    article: "32",
    title: "How to File a PIL",
    description: "Any citizen can approach High Court or Supreme Court for public welfare issues.",
    progress: 0,
    duration: "21 min",
    lessons: 6,
    users: 3200,
    rating: 4.8,
    level: "Advanced",
  },

  {
    id: 10,
    category: "Property Rights",
    icon: "🏠",
    article: "300A",
    title: "Property Ownership Rights",
    description: "You cannot be deprived of property except by authority of law.",
    progress: 0,
    duration: "19 min",
    lessons: 5,
    users: 2750,
    rating: 4.6,
    level: "Intermediate",
  },
];

export default modules;
